CREATE TABLE IF NOT EXISTS test_product(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  NAME VARCHAR(20) COMMENT '产品名称',
  PRICT BIGINT COMMENT '价格/分',
  CREATE_DATE DATETIME COMMENT '创建时间1'
);